version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reparaya_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: reparaya_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reparaya
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bbddReparaYa.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: reparaya_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  mysql_data: